// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TranDucHung289.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230104013124_TDH0289")]
    partial class TDH0289
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("TranDucHung289.Models.CompanyTDH289", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyTDH289");
                });

            modelBuilder.Entity("TranDucHung289.Models.TDH0289", b =>
                {
                    b.Property<string>("TDHid")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TDHGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TDHName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TDHid");

                    b.ToTable("TDH0289");
                });
#pragma warning restore 612, 618
        }
    }
}
